# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc75852091bae315e2f8714d51396248b98ea5bd6de7021adfb4bc812fe7e6d7217bbea69afc643e28e1c93ba173e0a87dfdfb252a1332b8d0d9ba1b3af38770

test:
  secret_key_base: 4616245e6078615a2a9d0133f902301d37fe3842b8b3a358a3bb0cb437ad0303066f89133eba6b1596cfdb32d75e337be9591552218d72e88e2fbc5754b2cd3f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
